name: pulse_dating_app
description: "A modern Flutter dating app with AR, WebRTC, and real-time features"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Networking
  dio: ^5.9.0
  http: ^1.5.0
  crypto: ^3.0.5

  # Offline Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1

  # Navigation
  go_router: ^16.2.1

  # Fonts
  google_fonts: ^6.2.1

  # Location
  geolocator: ^14.0.1


  # Utils
  path_provider: ^2.1.4
  get_it: ^8.2.0  # Added dependency injection
  sqlite3_flutter_libs: ^0.5.39
  socket_io_client: ^3.1.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  uuid: ^4.5.1
  logger: ^2.6.1
  connectivity_plus: ^7.0.0
  path: ^1.9.1
  sqlite3: ^2.9.0
  dartz: ^0.10.1
  image_cropper: ^8.0.2
  geocoding: ^2.2.2
  file_picker: ^8.1.4

  # Voice Messages
  just_audio: ^0.10.5
  audio_session: ^0.1.25
  # Virtual Gifts & Animations
  lottie: ^3.1.4
  flutter_animate: ^4.5.2

  # Safety Features
  device_info_plus: ^12.1.0

  # Push Notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1

  # Authentication
  local_auth: ^2.1.8
  flutter_secure_storage: ^8.1.0

  # Live Streaming
  camera: ^0.11.0+2
  iris_method_channel: ^2.2.4

  # Premium Features
  in_app_purchase: ^3.2.1
  purchases_flutter: ^9.6.2

  package_info_plus: ^8.3.1

  # Enhanced UI
  flutter_svg: ^2.1.1
  shimmer: ^3.0.0
  fluttertoast: ^9.0.0
  line_icons: ^2.0.3
  record: ^6.1.1
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.13.1
  url_launcher: ^6.3.2
  agora_rtc_engine: ^6.1.1
  image_picker: ^1.0.8
  flutter_image_compress: ^2.4.0
  video_player: ^2.8.8
  google_maps_cluster_manager: ^3.1.0
  google_polyline_algorithm: ^3.1.0
  photo_view: ^0.15.0
  google_maps_flutter_android: ^2.18.2
  google_maps_flutter_platform_interface: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Icon generation
  flutter_launcher_icons: ^0.14.1
  
  # Build tools
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  change_app_package_name: ^1.5.0
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/
  
  # Fonts - Using Google Fonts package for Poppins
  # No manual font files needed - google_fonts package handles it automatically

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#6E3BFF"  # Your brand primary color
  adaptive_icon_foreground: "assets/icon.png"
