name: pulse_dating_app
description: "A modern Flutter dating app with AR, WebRTC, and real-time features"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Networking
  dio: ^5.9.0
  http: ^1.5.0
  crypto: ^3.0.5

  # Offline Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1

  # Navigation
  go_router: ^16.2.1

  # Location
  geolocator: ^14.0.2

  # Permissions
  permission_handler: ^12.0.1

  # Utils
  path_provider: ^2.1.4
  get_it: ^8.2.0  # Added dependency injection
  sqlite3_flutter_libs: ^0.5.39
  socket_io_client: ^3.1.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  uuid: ^4.5.1
  logger: ^2.6.1
  connectivity_plus: ^6.1.5
  path: ^1.9.1
  sqlite3: ^2.9.0
  dartz: ^0.10.1
  image_picker: ^1.2.0
  image_cropper: ^8.0.2
  flutter_image_compress: ^2.3.0
  geocoding: ^3.0.0

  # Voice Messages
  audio_waveforms: ^1.0.5
  record: ^6.1.1
  just_audio: ^0.10.5

  # Virtual Gifts & Animations
  lottie: ^3.1.4
  flutter_animate: ^4.5.2

  # Safety Features
  # contacts_service: ^0.6.3  # Temporarily disabled due to namespace issues
  device_info_plus: ^11.2.1
  url_launcher: ^6.3.2

  # Authentication
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.2.2

  # Live Streaming
  camera: ^0.11.0+2
  agora_rtc_engine: ^6.3.3

  # Premium Features
  in_app_purchase: ^3.2.1
  purchases_flutter: ^8.1.3

  # Enhanced UI
  flutter_svg: ^2.1.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Icon generation
  flutter_launcher_icons: ^0.14.1
  
  # Build tools
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  change_app_package_name: ^1.5.0
flutter:
  uses-material-design: true

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#6E3BFF"  # Your brand primary color
  adaptive_icon_foreground: "assets/icon.png"
