name: pulse_dating_app
description: "A modern Flutter dating app with AR, WebRTC, and real-time features"
publish_to: 'none'

version: 1.0.5+5

environment:
  sdk: ^3.8.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Networking
  dio: ^5.9.0
  http: ^1.5.0
  crypto: ^3.0.5

  # Offline Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1

  # Navigation
  go_router: ^16.2.1

  # Fonts
  google_fonts: ^6.2.1

  # Location
  geolocator: ^14.0.1
  geocoding: ^4.0.0

  # Utils
  path_provider: ^2.1.4
  share_plus: ^12.0.0
  get_it: ^8.2.0  # Added dependency injection
  pdf: ^3.11.1  # PDF generation for transaction exports
  sqlite3_flutter_libs: ^0.5.40
  socket_io_client: ^3.1.2
  cached_network_image: ^3.4.1
  flutter_blurhash: ^0.8.2
  intl: ^0.20.2
  uuid: ^4.5.1
  logger: ^2.6.2
  connectivity_plus: ^7.0.0
  path: ^1.9.1
  sqlite3: ^2.9.2
  dartz: ^0.10.1
  image_cropper: ^11.0.0
  file_picker: ^10.3.3

  # Voice Messages
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  record: ^6.1.2
  audio_waveforms: ^1.1.0
  
  # Virtual Gifts & Animations
  lottie: ^3.1.4
  flutter_animate: ^4.5.2

  # Safety Features
  device_info_plus: ^12.1.0

  # Push Notifications
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  flutter_callkit_incoming: ^2.0.0+2

  # Authentication
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.0
  flutter_facebook_auth: ^6.0.3

  # Live Streaming
  camera: ^0.11.0+2
  iris_method_channel: ^2.2.4

  # Premium Features
  in_app_purchase: ^3.2.1
  in_app_purchase_storekit: ^0.3.10+1
  in_app_purchase_android: ^0.4.0+4
  purchases_flutter: ^9.8.0

  package_info_plus: ^9.0.0

  # Enhanced UI
  flutter_svg: ^2.1.1
  shimmer: ^3.0.0
  fluttertoast: ^9.0.0
  line_icons: ^2.0.3
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.13.1
  url_launcher: ^6.3.2
  agora_rtc_engine: ^6.1.1
  image_picker: ^1.0.8
  flutter_image_compress: ^2.4.0
  video_player: ^2.8.8
  google_maps_cluster_manager: ^3.1.0
  google_polyline_algorithm: ^3.1.0
  photo_view: ^0.15.0
  keyboard_dismisser: ^3.0.0
  keyboard_actions: ^4.1.0
  google_maps_flutter_android: ^2.18.2
  google_maps_flutter_platform_interface: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  # Icon generation
  flutter_launcher_icons: ^0.14.1
  
  # Build tools
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  change_app_package_name: ^1.5.0
  rename: ^3.1.0
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/
  
  # Fonts - Using Google Fonts package for Poppins
  # No manual font files needed - google_fonts package handles it automatically

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#6E3BFF"  # Your brand primary color
  adaptive_icon_foreground: "assets/icon.png"
