name: pulse_dating_app
description: "A modern Flutter dating app with AR, WebRTC, and real-time features"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1

  # Networking
  dio: ^5.9.0

  # Offline Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Navigation
  go_router: ^16.2.1

  # Location
  geolocator: ^14.0.2

  # Permissions
  permission_handler: ^12.0.1

  # Utils
  path_provider: ^2.1.4
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  json_serializable: ^6.11.0
  build_runner: ^2.7.1
  socket_io_client: ^3.1.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  uuid: ^4.5.1
  logger: ^2.6.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.1

flutter:
  uses-material-design: true
