name: pulse_dating_app
description: "A modern Flutter dating app with AR, WebRTC, and real-time features"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Networking
  dio: ^5.9.0

  # Offline Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.4

  # Navigation
  go_router: ^16.2.1

  # Location
  geolocator: ^14.0.2

  # Permissions
  permission_handler: ^12.0.1

  # Utils
  path_provider: ^2.1.4
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  json_serializable: ^6.11.1
  build_runner: ^2.7.2
  socket_io_client: ^3.1.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  uuid: ^4.5.1
  logger: ^2.6.1
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.5
  path: ^1.9.1
  sqlite3: ^2.9.0
  dartz: ^0.10.1
  image_picker: ^1.2.0

  # Voice Messages
  audio_waveforms: ^1.0.5
  record: ^6.1.1
  just_audio: ^0.10.5

  # Virtual Gifts & Animations
  lottie: ^3.1.4
  flutter_animate: ^4.5.2

  # Safety Features
  contacts_service: ^0.6.3
  device_info_plus: ^11.2.1
  url_launcher: ^6.3.2

  # Live Streaming
  camera: ^0.11.0+2
  agora_rtc_engine: ^6.3.3

  # Premium Features
  in_app_purchase: ^3.2.1
  purchases_flutter: ^8.1.3

  # Enhanced UI
  flutter_svg: ^2.1.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
